CREATE TABLE schema_metadata (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_name VARCHAR(100) NOT NULL,
    schema_version VARCHAR(30) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO schema_metadata (application_name, schema_version)
VALUES ('CalTalk', '1');
