CREATE TABLE schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    owner_user_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    location VARCHAR(200),
    start_at TIMESTAMP WITH TIME ZONE NOT NULL,
    end_at TIMESTAMP WITH TIME ZONE NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_schedules PRIMARY KEY (id),
    CONSTRAINT fk_schedules_owner FOREIGN KEY (owner_user_id) REFERENCES users (id),
    CONSTRAINT ck_schedules_time_range CHECK (end_at > start_at)
);

CREATE INDEX idx_schedules_owner_start ON schedules (owner_user_id, start_at);

CREATE TABLE confirmation_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    origin_channel VARCHAR(20) NOT NULL,
    command_type VARCHAR(30) NOT NULL,
    target_schedule_id BIGINT,
    target_schedule_version BIGINT,
    title VARCHAR(200),
    start_at TIMESTAMP WITH TIME ZONE,
    end_at TIMESTAMP WITH TIME ZONE,
    location_action VARCHAR(10) NOT NULL,
    location_value VARCHAR(200),
    candidate_fingerprint CHAR(64) NOT NULL,
    conflict_snapshot_hash CHAR(64) NOT NULL,
    conflict_acknowledged BOOLEAN NOT NULL DEFAULT FALSE,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    superseded_by_confirmation_id BIGINT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    consumed_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT pk_confirmation_requests PRIMARY KEY (id),
    CONSTRAINT fk_confirmation_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_confirmation_target FOREIGN KEY (target_schedule_id) REFERENCES schedules (id),
    CONSTRAINT fk_confirmation_superseded_by
        FOREIGN KEY (superseded_by_confirmation_id) REFERENCES confirmation_requests (id),
    CONSTRAINT ck_confirmation_origin
        CHECK (origin_channel IN ('PWA', 'WEB_CHAT', 'KAKAO')),
    CONSTRAINT ck_confirmation_command
        CHECK (command_type IN ('CREATE_EVENT', 'UPDATE_EVENT')),
    CONSTRAINT ck_confirmation_location_action
        CHECK (location_action IN ('KEEP', 'REMOVE', 'SET')),
    CONSTRAINT ck_confirmation_status
        CHECK (status IN ('PENDING', 'CONSUMED', 'SUPERSEDED', 'EXPIRED', 'CANCELLED'))
);

CREATE UNIQUE INDEX uq_confirmation_pending_candidate
    ON confirmation_requests (user_id, candidate_fingerprint)
    WHERE status = 'PENDING';
CREATE INDEX idx_confirmation_user_status ON confirmation_requests (user_id, status);
CREATE INDEX idx_confirmation_expires ON confirmation_requests (expires_at);
CREATE INDEX idx_confirmation_target_schedule ON confirmation_requests (target_schedule_id);

CREATE TABLE schedule_change_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    schedule_id BIGINT NOT NULL,
    changed_by_user_id BIGINT NOT NULL,
    source_channel VARCHAR(20) NOT NULL,
    change_type VARCHAR(20) NOT NULL,
    changed_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title_before VARCHAR(200),
    title_after VARCHAR(200),
    start_at_before TIMESTAMP WITH TIME ZONE,
    start_at_after TIMESTAMP WITH TIME ZONE,
    end_at_before TIMESTAMP WITH TIME ZONE,
    end_at_after TIMESTAMP WITH TIME ZONE,
    location_before VARCHAR(200),
    location_after VARCHAR(200),
    CONSTRAINT pk_schedule_change_history PRIMARY KEY (id),
    CONSTRAINT fk_history_schedule
        FOREIGN KEY (schedule_id) REFERENCES schedules (id) ON DELETE CASCADE,
    CONSTRAINT fk_history_changed_by FOREIGN KEY (changed_by_user_id) REFERENCES users (id),
    CONSTRAINT ck_history_source CHECK (source_channel IN ('PWA', 'WEB_CHAT', 'KAKAO')),
    CONSTRAINT ck_history_change_type CHECK (change_type IN ('CREATE', 'UPDATE', 'DELETE'))
);

CREATE INDEX idx_history_schedule
    ON schedule_change_history (schedule_id, changed_at);
CREATE INDEX idx_history_changed_by
    ON schedule_change_history (changed_by_user_id, changed_at);
