ALTER TABLE users ALTER COLUMN password_hash DROP NOT NULL;

CREATE TABLE social_identities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    provider VARCHAR(20) NOT NULL,
    provider_subject VARCHAR(255) NOT NULL,
    provider_email VARCHAR(254) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_social_identities PRIMARY KEY (id),
    CONSTRAINT fk_social_identities_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT uq_social_identities_provider_subject UNIQUE (provider, provider_subject),
    CONSTRAINT uq_social_identities_user_provider UNIQUE (user_id, provider)
);

CREATE INDEX idx_social_identities_user_id ON social_identities(user_id);
