CREATE TABLE kakao_user_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    logical_bot_key VARCHAR(100) NOT NULL,
    external_user_hmac VARCHAR(64) NOT NULL,
    linked_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_kakao_user_links_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT uq_kakao_user_links_user UNIQUE (user_id),
    CONSTRAINT uq_kakao_user_links_identity UNIQUE (logical_bot_key, external_user_hmac)
);

CREATE TABLE connection_codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    code_hmac VARCHAR(64) NOT NULL,
    issued_at TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    used_at TIMESTAMP WITH TIME ZONE,
    invalidated_at TIMESTAMP WITH TIME ZONE,
    fail_count INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT fk_connection_codes_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT ck_connection_codes_fail_count CHECK (fail_count >= 0 AND fail_count <= 5),
    CONSTRAINT uq_connection_codes_hmac UNIQUE (code_hmac)
);

CREATE INDEX idx_connection_codes_user ON connection_codes (user_id, issued_at DESC);
CREATE INDEX idx_connection_codes_active ON connection_codes (expires_at)
    WHERE used_at IS NULL AND invalidated_at IS NULL;
