spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
spring.session.jdbc.initialize-schema=never

server.servlet.session.cookie.secure=true
server.forward-headers-strategy=framework
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=30s

server.error.include-message=never
server.error.include-binding-errors=never
server.error.include-stacktrace=never
server.error.include-exception=false

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
management.endpoint.health.probes.enabled=true
management.health.redis.enabled=false

logging.level.root=INFO
logging.level.org.springframework.web=INFO
